[package]
name = "webrtc-audio-processing"
version = "0.1.0"
authors = ["Ryo Kawaguchi <ryo@kawagu.ch>"]
edition = "2018"
description = "A wrapper for WebRTC's AudioProcessing module."
documentation = "https://docs.rs/webrtc-audio-processing"
keywords = ["ffi"]
categories = ["multimedia::audio"]
license-file = "COPYING"

[badges]
travis-ci = { repository = "https://github.com/tonarino/webrtc-audio-processing", branch = "master" }
maintenance = { status = "actively-developed" }

[features]
derive_serde = ["webrtc-audio-processing-sys/derive_serde"]

[dependencies]
webrtc-audio-processing-sys = { path = "webrtc-audio-processing-sys" }
